markdown: rdiscount
name: Rough toughs
description: "Articles on the web front-end development, music and hiking."
url: http://blog.alienlebarge.ch
pygments: true
exclude: [Gruntfile.js, package.json, wordpress.xml, less, scss]
paginate: 5
excerpt_separator: <!--more-->
