markdown: rdiscount
name: Rough toughts
description: "Articles on the web front-end development, music and hiking."
pygments: true
exclude: [Gruntfile.js, package.json, wordpress.xml, less, scss]
paginate: 5
excerpt_separator: <!--more-->
